CREATE DATABASE co2;
CREATE TABLE co2.co2values(id VARCHAR(255), dt DATETIME, co2 SMALLINT UNSIGNED, temp FLOAT UNSIGNED);
CREATE USER co2user IDENTIFIED BY 'co2user';
GRANT SELECT, INSERT ON co2.co2values TO co2user;
